server:
  port: 6060 # 服务端口

sqlite:
  db:
    path: db/data.db # 数据库文件路径

spring:
  application:
    name: shard-file-upload # 服务名称
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/data.db # 数据库连接地址
    username:
    password:

mybatis-plus:
  # Mapper接口扫描包路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类所在包路径
  type-aliases-package: com.uluckyxh.shardfileupload.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启二级缓存
    cache-enabled: true
  global-config:
    db-config:
      # 主键生成策略
      id-type: auto

# 文件上传配置
file:
  upload:
    # 存储类型：LOCAL-本地存储
    storageType: LOCAL
    # 上传目录（相对于项目根目录）
    uploadDir: upload-files
    # 临时文件目录（存放分片文件）
    tempDir: upload-files/temp
    # 单个分片大小（MB）
    chunkSize: 5
    # 单文件大小限制（MB）
    maxFileSize: 5120  # 5GB = 5120MB

